
# Camera
FRAME_WIDTH = 1000
FRAME_HEIGHT = 540

# MediaPipe
NUM_HANDS = 2
MIN_DETECTION_CONFIDENCE = 0.45
MIN_PRESENCE_CONFIDENCE = 0.40
MIN_TRACKING_CONFIDENCE = 0.40
MODEL_PATH = "models/hand_landmarker.task"

# Steering
MAX_DEVIATION = 22
CENTER_ANGLE = -90
STEERING_OFFSET = 2

# Throttle
THROTTLE_LAG = 0.4
THROTTLE_RESPONSE = 0.6

# Dead zone  
# STEERING_DEAD_ZONE = 0.1